### PR TITLE
Fix the preprocessing actions

### PR DESCRIPTION
**Pull request by diml**
Preprocessing actions shouldn't manually redirect the output to `${@}` as dune already does this. This used to work, however it no longer works with dune >= 1.6.3 (see ocaml/dune#1811 for details).

We plan to make this a hard error in dune, to avoid other cases in the future.

### CODE REVIEW

**Comment by diml** [comment]
Do I need to sign a CLA for this patch? It is very small and trivial...

**Comment by AltGr** [comment]
You can ignore the CLA ;)
We should probably update the `opam` file to specify the minimum version of dune though ? (The dependency is still to `jbuilder`)

**Comment by Drup** [comment]
@AltGr We could just upgrade dune on the way, couldn't we ?

**Comment by diml** [comment]
Before this patch there should be a conflict with `dune >= 1.6.3`, but after this patch the conflict is no longer needed, i.e. the new code works with both old and new versions of dune. So we should update the opam file in the opam-repository, but it is not necessary to update the one in this repository.

Regarding moving to dune, we now have an automatic upgrader in dune master; running `dune upgrade` will convert the project to dune (except for the calls to jbuilder in the Makefile).

**Comment by AltGr** [comment]
great, thanks!

**Comment by Drup** [comment]
Let's merge, so that we can at least pin master! :)

**Comment by UnixJunkie** [comment]
There should be a bugfix release also.
Thanks!

**Pull request merged**
