### PR TITLE
META is missing a closing '"'

### PR DESCRIPTION
**Pull request by hcarty**

### CODE REVIEW

**Comment by AltGr** [comment]
Thanks!

**Comment by hcarty** [comment]
Thank you! Could a fix be pushed to opam? I think version 1.1.5 is affected.

**Comment by hcarty** [comment]
To be clearer - I'm willing to submit the opam PR if you'd prefer a patch against the latest release in opam to fix the typo.  if you prefer a new point release of ocp-index then I'll wait for that.

**Comment by AltGr** [comment]
As I am very busy with the opam release and upcoming OUD presentation, a PR would be highly appreciated. Thanks a lot!

**Comment by AltGr** [comment]
(simpler than a patch: just including the fixed META file inside the package's `files/` subdir would work)

**Pull request merged**
