### PR TITLE
Read include directories from .ocp-index

### PR DESCRIPTION
**Pull request by nojb**
See #76.

The behavior of `ocp-index` is left unchanged if no `.ocp-index` file is found in the tree.  If it is, then it used as project root and a list of include directories is read from it.  A new flag `--no-recursive` is added to complement this functionality.

### CODE REVIEW

**Comment by AltGr** [comment]
Two remarks:
- the `.ocp-index` file should be documented in `README.md`
- it would be good to prefix the directory names somehow in the file, in case we later want to add some more options to it. The best would be to follow the command-line options format, e.g. `I dir,dir`.

That's it, thanks a bunch!

**Comment by nojb** [comment]
Agree, will do it later today.  Thanks!

**Comment by nojb** [comment]
I have polished the patch; each line of `.ocp-index` file should be of the form `I "<dir>"` where `"<dir>"` follows the lexical conventions of OCaml.  With this I think the patch is ready for inclusion; if you agree I will rebase and squash everything into a single commit.

**Comment by rgrinberg** [comment]
I think this is a nice feature but as a user I'm a bit annoyed that I have to maintain yet another config file with this random metadata.

Would it be possible for ocp-index to simply read build folder directories from .merlin files? For example:
https://github.com/ocaml/ocaml/blob/trunk/.merlin#L2

This example also shows how widely useful this might be as there are already quite a few .merlin's out there.

**Comment by AltGr** [comment]
Oh, sorry @nojb, I had completely forgotten about this, wouldn't it have been for @rgrinberg's remark. He actually has quite a point, if all the information we might need is already available in .merlin files, adding a new file format is superfluous, and I'd be quite happy to re-use them, esp. as it's nicer on the users.

The only downside I can see is that if a project has an out of sync or wrong .merlin, it would hurt ocp-index while the heuristics might have worked; but I don't think it's a worthwile concern.

The good news is that @nojb's contribution would need very little changes to use .merlin files.

**Comment by nojb** [comment]
Sure, sounds like a good idea! I will try to to take a look at this today and make the necessary changes.

Thanks!

**Comment by nojb** [comment]
Just a quick update:  I looked at this but it is not so easy because .merlin files supports patterns.  We could re-implement the merlin logic in ocp-index but it is not so nice.  We could also ask the merlin people to release a tiny library to read .merlin files so that we could reuse that.

**Comment by AltGr** [comment]
Indeed, that may be more complicated than we first thought, and the code seems [non](https://github.com/the-lambda-church/merlin/blob/63bc3bf7aad2e22f0a1b5907a21a6c9bb00c2de7/src/utils/std.ml#L701-L800) [trivial](https://github.com/the-lambda-church/merlin/blob/63bc3bf7aad2e22f0a1b5907a21a6c9bb00c2de7/src/utils/misc.ml#L92-L126).

Also, I didn't read the full spec, but I am not sure `.merlin` files are necessarily at the root of the project?
Not sure where to go next, thus, `.ocp-indent` files with syntax a subset of `.merlin` files (so that users don't have to learn anything new) ? Form a consortium to define a common `.project` file format with a separate lib ?

**Comment by hcarty** [comment]
A shared .project format used across all of these editor/exploration tools would be very nice to have.  One format would make it easy enough to create a tool or suite of tools to automatically extract the relevant details from an oasis/ocp-build/obuild/etc build configuration.

**Comment by let-def** [comment]
I would be happy to provide a library for reading .merlin files (probably as part of [let-def/merlin-extend](http://github.com/let-def/merlin-extend)).
But I am interested in a more generic `.project` description also.

**Comment by XVilka** [comment]
Should be this either updated or closed?

**Comment by nojb** [comment]
We have since switched to `merlin` for editor support, so we are not affected by this anymore.

**Pull request closed without merging**
