### PR TITLE
Add support for OCaml 4.12

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Equivalence between `(true, true)` and `(NoVariance, NoInjectivity)` can be found in this commit: https://github.com/ocaml/ocaml/commit/603506aa34d0e5f7a9745c988777776ccb734094

### CODE REVIEW

**Comment by Drup** [comment]
We need to do something about CI ._.

The patch looks good. @AltGr ?

**Comment by kit-ty-kate** [comment]
https://github.com/OCamlPro/ocp-index/commit/a4d9a2e22a511eeba08b769411b1304679151909 broke ocp-browser on OCaml 4.12, I fixed that in ecc36c7 and added OCaml up to 4.12 in CI.

**Comment by kit-ty-kate** [comment]
Ultimately I suggest you to switch to github actions but this can wait and as far as I know it's nothing I can do on my own as a contributor AFAIK.

**Comment by kit-ty-kate** [comment]
Could someone with the appropriate rights enable Github Actions?

**Comment by kit-ty-kate** [comment]
Github Actions apparently can't be enabled via a PR. So it should be enabled automatically once this PR is merged.
Here is the CI result from this run: https://github.com/kit-ty-kate/ocp-index/actions/runs/559595363
Everything is green so this should be good to go.

**Comment by AltGr** [comment]
Thanks!

**Comment by kit-ty-kate** [comment]
would it be possible to have a release whenever one of you two have some time?

**Pull request merged**
