### PR TITLE
OCaml 4.11 and lambda-term 3.0 support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
This PR brings OCaml 4.11 support as well as lambda-term 3.0 support. The later is not compatible due to a new library required by lambda-term called `trie` which clashes with the `Trie` module. The later was the only one without any sort of prefixing in the ocp-index library.

I'm not sure if this breaks some packages relying on the ocp-index library though.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
for the record, the OCaml 4.11 support relies on https://github.com/OCamlPro/ocp-build/pull/126

**Comment by Drup** [comment]
Looks good. Merging!

Why is ocp-build needed ? ocp-index/browser builds with dune now.

**Comment by kit-ty-kate** [comment]
@Drup the PR linked above fixes `ocp-pp` not `ocp-build`. `ocp-index` relies on `ocp-pp` to build in the following places: https://github.com/OCamlPro/ocp-index/blob/ac249ee063c31e9118845a154da9c4d243f7cb8e/src/dune#L17

**Comment by AltGr** [comment]
Awesome, thanks a lot!
I'd probably have just put `module Trie = IndexTrie` at the top of the file, seems you're less lazy than me ;)

**Pull request merged**
